import Foundation

// Checks the scripts and plugins Coucou writes for the agents
// (NotchBuddy/Sources/App/HookRelayScripts.swift), then writes them into the folder given
// as the first argument so scripts/test-hook-relay.sh can run them (tests/hook_relay_check.py).

@main
enum HookRelayScriptsTests {
    static func main() throws {
        var count = 0
        func check(_ condition: Bool, _ message: String) {
            precondition(condition, message)
            count += 1
        }

        // The two Python relays are one script: only the header and the socket path differ.
        let githubHeader = """
        # nb-hook.py — Coucou hook relay for Claude Code and third-party agents (GitHub version)
        # Reads JSON from stdin, forwards to Coucou via Unix socket, translates response.
        """
        let appStoreHeader = """
        # nb-hook.py — Coucou (App Store) hook relay for Claude Code and third-party agents
        # Socket lives inside the sandboxed container; script runs outside the sandbox.
        """
        let githubSocket = "'~/Library/Application Support/NotchBuddy/nb.sock'"
        let appStoreSocket = "'~/Library/Containers/fr.louisraille.Coucou/Data/nb.sock'"
        check(nbHookPythonGitHub.contains(githubHeader) && nbHookPythonGitHub.contains(githubSocket), "GitHub relay")
        check(nbHookPythonAppStore.contains(appStoreHeader) && nbHookPythonAppStore.contains(appStoreSocket), "App Store relay")
        check(nbHookPythonGitHub.replacingOccurrences(of: githubHeader, with: appStoreHeader)
                .replacingOccurrences(of: githubSocket, with: appStoreSocket) == nbHookPythonAppStore,
              "the relays differ only by header and socket path")
        check(nbHookPythonGitHub.hasPrefix("#!/usr/bin/env python3\n"), "shebang")
        check(!nbHookPythonGitHub.contains("\\("), "no Swift interpolation left in the relay")

        // The wrapper never blocks: it always ends with exit 0.
        check(nbHookShellWrapper.hasPrefix("#!/bin/sh\n"), "wrapper shebang")
        check(nbHookShellWrapper.hasSuffix("exit 0"), "wrapper exits 0")

        // The Hermes transport falls back to Hermes' own prompt — it never denies by itself.
        let hermes = hermesPluginSource(hookPath: "/tmp/x/nb-hook")
        check(!hermes.contains("return request.respond('deny')"), "Hermes plugin never answers deny on its own")
        check(hermes.contains("generated by Coucou"), "Hermes plugin marker")
        check(hermesPluginYaml.contains("generated by Coucou.app"), "plugin.yaml marker")

        // Paths are escaped into single-quoted JS/Python literals.
        let odd = #"/Users/o'neil\x/Library/Application Support/NotchBuddy/nb-hook"#
        let escaped = #"'/Users/o\'neil\\x/Library/Application Support/NotchBuddy/nb-hook'"#
        check(openCodePluginSource(hookPath: odd).contains("const HOOK = \(escaped);"), "OpenCode path escaping")
        check(ampPluginSource(hookPath: odd).contains("const HOOK = \(escaped);"), "Amp path escaping")
        check(hermesPluginSource(hookPath: odd).contains("HOOK = Path(\(escaped))"), "Hermes path escaping")
        for source in [openCodePluginSource(hookPath: odd), ampPluginSource(hookPath: odd)] {
            check(source.contains("generated by Coucou"), "plugin marker (removal checks it)")
        }

        // Write everything out for the Python checks.
        let args = CommandLine.arguments
        if args.count > 1 {
            let dir = URL(fileURLWithPath: args[1])
            let fm = FileManager.default
            try fm.createDirectory(at: dir.appendingPathComponent("hermes_coucou"), withIntermediateDirectories: true)
            try nbHookShellWrapper.write(to: dir.appendingPathComponent("nb-hook"), atomically: true, encoding: .utf8)
            try nbHookPythonGitHub.write(to: dir.appendingPathComponent("nb-hook.py"), atomically: true, encoding: .utf8)
            try nbHookPythonAppStore.write(to: dir.appendingPathComponent("nb-hook-appstore.py"), atomically: true, encoding: .utf8)
            try hermesPluginSource(hookPath: dir.appendingPathComponent("fake-hook").path)
                .write(to: dir.appendingPathComponent("hermes_coucou/__init__.py"), atomically: true, encoding: .utf8)
            for name in ["nb-hook", "nb-hook.py"] {
                try fm.setAttributes([.posixPermissions: NSNumber(value: 0o755)],
                                     ofItemAtPath: dir.appendingPathComponent(name).path)
            }
        }

        print("Hook relay scripts: \(count) checks passed")
    }
}
